services:
  redis:
    image: redis:7.2.3
    ports:
      - 6379:6379
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 9001:8080
